-- =====================================================================
-- V1: Baseline schema (full)
-- Sinh từ schema thực tế do JPA/Hibernate tạo (37 bảng, đã gồm
-- cột workouts_per_week). Đây là nguồn schema chuẩn cho production.
-- ddl-auto=validate ở prod sẽ kiểm tra entities khớp với schema này.
-- =====================================================================

--
-- PostgreSQL database dump
--


-- Dumped from database version 16.13
-- Dumped by pg_dump version 16.13

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: ai_evaluation_logs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ai_evaluation_logs (
    ael_id bigint NOT NULL,
    completed_at timestamp(6) with time zone,
    confidence double precision,
    created_at timestamp(6) with time zone,
    error_message text,
    input_payload json,
    input_video_url text,
    model_name character varying(100),
    model_version character varying(50),
    notes text,
    output_payload json,
    processing_time_ms bigint,
    score integer,
    started_at timestamp(6) with time zone,
    status character varying(20) NOT NULL,
    challenge_id bigint NOT NULL,
    user_id bigint NOT NULL,
    user_challenge_id bigint,
    CONSTRAINT ai_evaluation_logs_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'PROCESSING'::character varying, 'COMPLETED'::character varying, 'FAILED'::character varying, 'TIMEOUT'::character varying])::text[])))
);


--
-- Name: ai_evaluation_logs_ael_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.ai_evaluation_logs ALTER COLUMN ael_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ai_evaluation_logs_ael_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ai_model_events; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ai_model_events (
    event_id bigint NOT NULL,
    confidence double precision,
    created_at timestamp(6) with time zone,
    exercise_type character varying(50),
    model_name character varying(200),
    model_version character varying(50),
    passed boolean,
    quality_score double precision,
    reps integer,
    result_json text,
    challenge_id bigint,
    exercise_id bigint,
    user_id bigint NOT NULL,
    uc_id bigint NOT NULL
);


--
-- Name: ai_model_events_event_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.ai_model_events ALTER COLUMN event_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ai_model_events_event_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: body_metric_history; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.body_metric_history (
    bmh_id bigint NOT NULL,
    arm_cm numeric(5,2),
    bmi numeric(5,2),
    bmr_calculated numeric(7,2),
    body_fat_pct numeric(5,2),
    chest_cm numeric(5,2),
    created_at timestamp(6) with time zone,
    deleted_at timestamp(6) with time zone,
    device_id character varying(100),
    height_cm numeric(5,2),
    hip_cm numeric(5,2),
    is_deleted boolean,
    muscle_mass_kg numeric(6,2),
    notes text,
    recorded_at timestamp(6) with time zone NOT NULL,
    source character varying(30),
    tdee_calculated numeric(7,2),
    thigh_cm numeric(5,2),
    updated_at timestamp(6) with time zone,
    waist_cm numeric(5,2),
    waist_hip_ratio numeric(4,2),
    water_pct numeric(5,2),
    weight_kg numeric(6,2) NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: body_metric_history_bmh_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.body_metric_history ALTER COLUMN bmh_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.body_metric_history_bmh_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: budget_tracking; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.budget_tracking (
    bt_id bigint NOT NULL,
    actual_spent integer,
    ai_stayed_within_budget boolean,
    budget_notes text,
    created_at timestamp(6) with time zone,
    daily_budget integer,
    purchased_items_json text,
    tracking_date date NOT NULL,
    updated_at timestamp(6) with time zone,
    variance integer,
    week_start_date date,
    weekly_budget integer,
    weekly_remaining integer,
    weekly_spent integer,
    pnp_id bigint,
    user_id bigint NOT NULL
);


--
-- Name: budget_tracking_bt_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.budget_tracking ALTER COLUMN bt_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.budget_tracking_bt_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: challenge_exercises; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.challenge_exercises (
    challenge_id bigint NOT NULL,
    exercise_id bigint NOT NULL
);


--
-- Name: challenges; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.challenges (
    challenge_id bigint NOT NULL,
    ai_rules_json text,
    created_at timestamp(6) with time zone,
    description text,
    duration_days integer,
    end_date date,
    reward character varying(200),
    reward_points integer,
    start_date date,
    status character varying(20),
    title character varying(200),
    updated_at timestamp(6) with time zone,
    goal_id bigint,
    CONSTRAINT challenges_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying, 'DRAFT'::character varying, 'COMPLETED'::character varying])::text[])))
);


--
-- Name: challenges_challenge_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.challenges ALTER COLUMN challenge_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.challenges_challenge_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: daily_nutrition_logs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.daily_nutrition_logs (
    dnl_id bigint NOT NULL,
    calories numeric(38,2),
    carbs numeric(38,2),
    cost integer,
    created_at timestamp(6) with time zone,
    fat numeric(38,2),
    meal_name character varying(255),
    meal_type character varying(255),
    protein numeric(38,2),
    tracking_date date NOT NULL,
    water_liters numeric(38,2),
    user_id bigint NOT NULL
);


--
-- Name: daily_nutrition_logs_dnl_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.daily_nutrition_logs ALTER COLUMN dnl_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.daily_nutrition_logs_dnl_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: daily_training_logs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.daily_training_logs (
    dtl_id bigint NOT NULL,
    actual_duration_minutes integer,
    calories_burned integer,
    completed_at timestamp(6) with time zone,
    confidence double precision,
    created_at timestamp(6) with time zone,
    day_number integer NOT NULL,
    deleted_at timestamp(6) with time zone,
    effort_level integer,
    fatigue_level integer,
    is_deleted boolean,
    notes text,
    perceived_difficulty integer,
    reps_completed integer,
    score integer,
    sets_completed integer,
    sleep_hours double precision,
    started_at timestamp(6) with time zone,
    status character varying(20) NOT NULL,
    training_date date NOT NULL,
    updated_at timestamp(6) with time zone,
    exercise_id bigint,
    tp_id bigint NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT daily_training_logs_status_check CHECK (((status)::text = ANY ((ARRAY['NOT_STARTED'::character varying, 'IN_PROGRESS'::character varying, 'COMPLETED'::character varying, 'SKIPPED'::character varying])::text[])))
);


--
-- Name: daily_training_logs_dtl_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.daily_training_logs ALTER COLUMN dtl_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.daily_training_logs_dtl_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: dish_ingredients; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.dish_ingredients (
    dish_ingredient_id bigint NOT NULL,
    is_core_ingredient boolean NOT NULL,
    dish_id bigint NOT NULL,
    food_id bigint NOT NULL
);


--
-- Name: dish_ingredients_dish_ingredient_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.dish_ingredients ALTER COLUMN dish_ingredient_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.dish_ingredients_dish_ingredient_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: dishes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.dishes (
    dish_id bigint NOT NULL,
    dish_name character varying(255) NOT NULL,
    dish_role character varying(30) NOT NULL,
    image_url character varying(1000),
    is_active boolean,
    suitable_meal_types character varying(120),
    CONSTRAINT dishes_dish_role_check CHECK (((dish_role)::text = ANY ((ARRAY['MAIN_PROTEIN'::character varying, 'SOUP'::character varying, 'VEGETABLE'::character varying, 'CARB_BASE'::character varying, 'ONE_POT'::character varying])::text[])))
);


--
-- Name: dishes_dish_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.dishes ALTER COLUMN dish_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.dishes_dish_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: exercises; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.exercises (
    exercise_id bigint NOT NULL,
    contraindicated_injuries text,
    default_reps integer,
    default_rest_seconds integer,
    default_sets integer,
    description text,
    difficulty_level character varying(30),
    equipment_alternatives text,
    estimated_met integer,
    exercise_category character varying(30),
    exercise_name character varying(200),
    exercise_name_vi character varying(200),
    exercise_type character varying(80),
    force_type character varying(20),
    high_impact boolean,
    image_url character varying(500),
    is_bilateral boolean,
    knee_dominant boolean,
    met_value numeric(4,1),
    movement_pattern character varying(80),
    primary_muscle character varying(100),
    required_equipment character varying(80),
    rpe_max smallint,
    rpe_min smallint,
    secondary_muscles text,
    shoulder_overhead boolean,
    spinal_loading boolean,
    status character varying(20),
    suitable_for_overweight boolean,
    suitable_for_senior boolean,
    tempo character varying(15),
    video_url text,
    wrist_loading boolean,
    progression_exercise_id bigint,
    regression_exercise_id bigint,
    CONSTRAINT exercises_difficulty_level_check CHECK (((difficulty_level)::text = ANY ((ARRAY['EASY'::character varying, 'MEDIUM'::character varying, 'HARD'::character varying])::text[])))
);


--
-- Name: exercises_exercise_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.exercises ALTER COLUMN exercise_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.exercises_exercise_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: food_allergens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.food_allergens (
    food_id bigint NOT NULL,
    allergen character varying(255),
    CONSTRAINT food_allergens_allergen_check CHECK (((allergen)::text = ANY ((ARRAY['GLUTEN'::character varying, 'DAIRY'::character varying, 'NUTS'::character varying, 'SEAFOOD'::character varying, 'EGGS'::character varying, 'SOY'::character varying, 'PEANUTS'::character varying, 'SHELLFISH'::character varying])::text[])))
);


--
-- Name: foods; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.foods (
    food_id bigint NOT NULL,
    average_market_price_vnd integer,
    calories_per_100g integer,
    carbs_per_100g numeric(5,2),
    category character varying(30),
    cooking_method character varying(20),
    fat_per_100g numeric(5,2),
    fiber_per_100g numeric(5,2),
    grams_per_piece numeric(8,2),
    image_url character varying(500),
    is_vegan boolean,
    meal_type_tags character varying(100),
    name character varying(200) NOT NULL,
    notes character varying(255),
    prep_state character varying(20),
    protein_per_100g numeric(5,2),
    serving_unit character varying(20),
    sodium_per_100mg numeric(7,2),
    sugar_per_100g numeric(5,2),
    vietnamese_name character varying(200),
    CONSTRAINT foods_cooking_method_check CHECK (((cooking_method)::text = ANY ((ARRAY['RAW'::character varying, 'BOILED'::character varying, 'FRIED'::character varying, 'STEAMED'::character varying, 'GRILLED'::character varying, 'COOKED'::character varying])::text[]))),
    CONSTRAINT foods_prep_state_check CHECK (((prep_state)::text = ANY ((ARRAY['RAW'::character varying, 'COOKED'::character varying])::text[]))),
    CONSTRAINT foods_serving_unit_check CHECK (((serving_unit)::text = ANY ((ARRAY['GRAM'::character varying, 'PIECE'::character varying])::text[])))
);


--
-- Name: foods_food_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.foods ALTER COLUMN food_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.foods_food_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: goals; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.goals (
    goal_id bigint NOT NULL,
    descriptions character varying(255),
    image_link character varying(255),
    name character varying(255)
);


--
-- Name: goals_goal_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.goals ALTER COLUMN goal_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.goals_goal_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: health_profile; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.health_profile (
    id bigint NOT NULL,
    alcohol_consumption character varying(20),
    available_equipment character varying(200),
    body_fat_percent numeric(5,2),
    body_image_url character varying(500),
    created_at timestamp(6) with time zone,
    current_diet_type character varying(50),
    current_injuries text,
    daily_activity_level character varying(50),
    deleted_at timestamp(6) with time zone,
    favorite_exercise_type character varying(100),
    frequent_foods text,
    goal_body_fat_percent numeric(5,2),
    goal_description text,
    goal_timeline_days integer,
    goal_weight_kg numeric(6,2),
    hip_cm numeric(38,2),
    is_deleted boolean,
    lean_body_mass_kg numeric(6,2),
    meals_per_day integer,
    medical_history text,
    mobility_level character varying(20),
    neck_cm numeric(38,2),
    occupation character varying(100),
    primary_goal character varying(50),
    sleep_hours_per_day integer,
    smoking_status character varying(20),
    stress_level character varying(20),
    updated_at timestamp(6) with time zone,
    waist_cm numeric(38,2),
    water_intake_liters_per_day numeric(4,2),
    workout_frequency_per_week integer,
    user_id bigint NOT NULL
);


--
-- Name: health_profile_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.health_profile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.health_profile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: information_body_user; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.information_body_user (
    info_id bigint NOT NULL,
    activity_level character varying(50),
    age integer NOT NULL,
    bmi numeric(5,2),
    bmr numeric(8,2),
    body_fat_pct numeric(5,2),
    created_at timestamp(6) with time zone,
    gender character varying(20) NOT NULL,
    height_cm numeric(5,2) NOT NULL,
    recommended_calories numeric(8,0),
    weight_kg numeric(6,2) NOT NULL,
    goal_id bigint,
    user_id bigint NOT NULL
);


--
-- Name: information_body_user_info_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.information_body_user ALTER COLUMN info_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.information_body_user_info_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notifications; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notifications (
    notification_id bigint NOT NULL,
    content text NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    icon_url text,
    is_read boolean NOT NULL,
    link_url text,
    read_at timestamp(6) with time zone,
    send_status character varying(20) NOT NULL,
    sent_at timestamp(6) with time zone,
    sent_via_email boolean,
    sent_via_in_app boolean,
    sent_via_push boolean,
    title character varying(200) NOT NULL,
    type character varying(50) NOT NULL,
    updated_at timestamp(6) with time zone,
    user_id bigint NOT NULL,
    CONSTRAINT notifications_send_status_check CHECK (((send_status)::text = ANY ((ARRAY['PENDING'::character varying, 'SENT'::character varying, 'FAILED'::character varying])::text[])))
);


--
-- Name: notifications_notification_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.notifications ALTER COLUMN notification_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notifications_notification_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: personalized_meal_details; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.personalized_meal_details (
    pmd_id bigint NOT NULL,
    ai_prompt_version character varying(50),
    cooking_instructions text,
    created_at timestamp(6) with time zone,
    day_number integer NOT NULL,
    estimated_cost integer,
    meal_items_json text,
    meal_type character varying(20) NOT NULL,
    prep_time_minutes integer,
    skip_reason character varying(255),
    total_calories double precision,
    total_carbs double precision,
    total_fat double precision,
    total_protein double precision,
    updated_at timestamp(6) with time zone,
    user_feedback text,
    user_rating integer,
    was_eaten boolean,
    dish_id bigint,
    pnp_id bigint NOT NULL,
    CONSTRAINT personalized_meal_details_meal_type_check CHECK (((meal_type)::text = ANY ((ARRAY['BREAKFAST'::character varying, 'LUNCH'::character varying, 'DINNER'::character varying, 'SNACK'::character varying])::text[])))
);


--
-- Name: personalized_meal_details_pmd_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.personalized_meal_details ALTER COLUMN pmd_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.personalized_meal_details_pmd_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: personalized_meal_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.personalized_meal_items (
    pmi_id bigint NOT NULL,
    from_inventory boolean NOT NULL,
    line_calories double precision,
    line_carbs double precision,
    line_cost_vnd integer,
    line_fat double precision,
    line_protein double precision,
    quantity_grams numeric(10,2) NOT NULL,
    dish_id bigint,
    food_id bigint NOT NULL,
    pmd_id bigint NOT NULL
);


--
-- Name: personalized_meal_items_pmi_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.personalized_meal_items ALTER COLUMN pmi_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.personalized_meal_items_pmi_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: personalized_nutrition_plans; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.personalized_nutrition_plans (
    pnp_id bigint NOT NULL,
    actual_total_cost integer,
    ai_generation_context text,
    ai_plan_id character varying(100),
    ai_prompt_version character varying(50),
    ai_response_json text,
    created_at timestamp(6) with time zone,
    deleted_at timestamp(6) with time zone,
    duration_days integer,
    end_date date,
    estimated_total_cost integer,
    generation_notes text,
    is_deleted boolean,
    start_date date,
    status character varying(20) NOT NULL,
    target_budget_per_day integer,
    target_calories double precision,
    target_carbs double precision,
    target_fat double precision,
    target_protein double precision,
    updated_at timestamp(6) with time zone,
    version integer,
    user_id bigint NOT NULL,
    CONSTRAINT personalized_nutrition_plans_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'COMPLETED'::character varying, 'CANCELLED'::character varying, 'ARCHIVED'::character varying, 'EXPIRED'::character varying])::text[])))
);


--
-- Name: personalized_nutrition_plans_pnp_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.personalized_nutrition_plans ALTER COLUMN pnp_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.personalized_nutrition_plans_pnp_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: personalized_plan_detail; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.personalized_plan_detail (
    ppd_id bigint NOT NULL,
    day_number integer NOT NULL,
    difficulty character varying(50) NOT NULL,
    estimated_calories integer,
    exercise_name character varying(200) NOT NULL,
    notes character varying(500),
    recommended_weight character varying(50),
    reps integer NOT NULL,
    rest_time integer,
    sets integer NOT NULL,
    target_muscle character varying(100),
    tpd_id bigint,
    ut_id bigint,
    exercise_id bigint,
    user_id bigint NOT NULL
);


--
-- Name: personalized_plan_detail_ppd_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.personalized_plan_detail ALTER COLUMN ppd_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.personalized_plan_detail_ppd_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: plan_version_history; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.plan_version_history (
    pvh_id bigint NOT NULL,
    ai_version_id character varying(100),
    change_summary text,
    created_at timestamp(6) with time zone,
    deleted_at timestamp(6) with time zone,
    diff_json text,
    estimated_cost integer,
    is_current boolean,
    is_deleted boolean,
    plan_data_json text,
    plan_id bigint NOT NULL,
    plan_type character varying(20) NOT NULL,
    status character varying(20),
    target_calories double precision,
    target_protein double precision,
    version_number integer NOT NULL,
    parent_version_id bigint,
    user_id bigint NOT NULL,
    CONSTRAINT plan_version_history_plan_type_check CHECK (((plan_type)::text = ANY ((ARRAY['NUTRITION'::character varying, 'WORKOUT'::character varying, 'TRAINING'::character varying])::text[]))),
    CONSTRAINT plan_version_history_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'ARCHIVED'::character varying, 'REVERTED'::character varying])::text[])))
);


--
-- Name: plan_version_history_pvh_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.plan_version_history ALTER COLUMN pvh_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.plan_version_history_pvh_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: program_templates; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.program_templates (
    id bigint NOT NULL,
    adaptation_notes text,
    base_reps integer NOT NULL,
    base_rest_seconds integer NOT NULL,
    base_sets integer NOT NULL,
    created_at timestamp(6) with time zone,
    duration_minutes integer NOT NULL,
    exercise_pool_json text NOT NULL,
    goal character varying(50) NOT NULL,
    intensity character varying(30),
    progression_rate double precision NOT NULL,
    status character varying(20) NOT NULL,
    training_plan_id bigint NOT NULL,
    updated_at timestamp(6) with time zone,
    user_id bigint NOT NULL,
    ut_id bigint NOT NULL,
    version_number integer NOT NULL,
    weekly_pattern_json text NOT NULL
);


--
-- Name: program_templates_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.program_templates ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.program_templates_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reports; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.reports (
    report_id bigint NOT NULL,
    adjusted_score integer,
    admin_response text,
    created_at timestamp(6) with time zone NOT NULL,
    description text NOT NULL,
    evidence_url text,
    report_type character varying(50) NOT NULL,
    resolution_action character varying(50),
    resolved_at timestamp(6) with time zone,
    status character varying(20) NOT NULL,
    title character varying(200) NOT NULL,
    updated_at timestamp(6) with time zone,
    ai_evaluation_log_id bigint,
    assigned_to_user_id bigint,
    challenge_id bigint,
    user_id bigint NOT NULL,
    user_challenge_id bigint,
    CONSTRAINT reports_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'UNDER_REVIEW'::character varying, 'RESOLVED'::character varying, 'REJECTED'::character varying, 'CLOSED'::character varying])::text[])))
);


--
-- Name: reports_report_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.reports ALTER COLUMN report_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reports_report_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reward_redemptions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.reward_redemptions (
    rr_id bigint NOT NULL,
    created_at timestamp(6) with time zone,
    fulfilled_at timestamp(6) with time zone,
    status character varying(20) NOT NULL,
    reward_id bigint NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT reward_redemptions_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'FULFILLED'::character varying, 'CANCELLED'::character varying])::text[])))
);


--
-- Name: reward_redemptions_rr_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.reward_redemptions ALTER COLUMN rr_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reward_redemptions_rr_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: rewards; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.rewards (
    reward_id bigint NOT NULL,
    claimed integer,
    cost_points integer,
    created_at timestamp(6) with time zone,
    description character varying(255),
    expire_at timestamp(6) with time zone,
    external_partner character varying(200),
    link_image character varying(255),
    name character varying(200) NOT NULL,
    status character varying(20),
    stock integer NOT NULL
);


--
-- Name: rewards_reward_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.rewards ALTER COLUMN reward_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.rewards_reward_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: roles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.roles (
    role_id bigint NOT NULL,
    description character varying(255),
    role_name character varying(255)
);


--
-- Name: roles_role_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.roles ALTER COLUMN role_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.roles_role_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: training_plan_details; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.training_plan_details (
    tpd_id bigint NOT NULL,
    day_number integer NOT NULL,
    duration integer,
    instructions text,
    reps integer,
    rest_time integer,
    sets integer DEFAULT 1,
    exercise_id bigint,
    tp_id bigint
);


--
-- Name: training_plan_details_tpd_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.training_plan_details ALTER COLUMN tpd_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.training_plan_details_tpd_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: training_plans; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.training_plans (
    tp_id bigint NOT NULL,
    created_at timestamp(6) with time zone,
    deleted_at timestamp(6) with time zone,
    description character varying(255),
    difficulty_level character varying(20),
    duration_weeks integer,
    is_deleted boolean,
    title character varying(200) NOT NULL,
    workouts_per_week integer,
    goal_id bigint
);


--
-- Name: training_plans_tp_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.training_plans ALTER COLUMN tp_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.training_plans_tp_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: transactions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.transactions (
    tx_id bigint NOT NULL,
    amount numeric(12,2),
    created_at timestamp(6) with time zone,
    description character varying(255),
    points integer,
    reference character varying(255),
    status character varying(20) NOT NULL,
    type character varying(50) NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT transactions_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'COMPLETED'::character varying, 'FAILED'::character varying, 'CANCELLED'::character varying])::text[])))
);


--
-- Name: transactions_tx_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.transactions ALTER COLUMN tx_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.transactions_tx_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_body_profile; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_body_profile (
    id bigint NOT NULL,
    activity_level character varying(50),
    age integer,
    bmi numeric(5,2),
    bmr numeric(8,2),
    body_fat numeric(5,2),
    created_at timestamp(6) with time zone,
    experience_level character varying(20),
    gender character varying(20),
    goal character varying(50),
    height numeric(6,2),
    injury_notes text,
    muscle_mass numeric(6,2),
    recommended_calories numeric(8,0),
    target_budget_per_day integer,
    updated_at timestamp(6) with time zone,
    weight numeric(6,2),
    goal_id bigint,
    user_id bigint NOT NULL
);


--
-- Name: user_body_profile_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.user_body_profile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_body_profile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_challenges; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_challenges (
    uc_id bigint NOT NULL,
    completed_at timestamp(6) with time zone,
    confidence double precision,
    deleted_at timestamp(6) with time zone,
    is_deleted boolean,
    keypoints_payload text,
    score integer,
    status character varying(20) NOT NULL,
    submitted_at timestamp(6) with time zone,
    video_url text,
    challenge_id bigint NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT user_challenges_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'SUCCESS'::character varying, 'FAILED'::character varying, 'DISPUTED'::character varying])::text[])))
);


--
-- Name: user_challenges_uc_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.user_challenges ALTER COLUMN uc_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_challenges_uc_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_inventory; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_inventory (
    inventory_id bigint NOT NULL,
    added_at timestamp(6) with time zone,
    ai_suggestion_note text,
    deleted_at timestamp(6) with time zone,
    expiry_date date,
    food_name character varying(255),
    is_deleted boolean,
    quantity_grams double precision,
    status character varying(20) NOT NULL,
    unit character varying(50),
    updated_at timestamp(6) with time zone,
    used_in_plan boolean,
    food_id bigint,
    user_id bigint NOT NULL,
    CONSTRAINT user_inventory_status_check CHECK (((status)::text = ANY ((ARRAY['AVAILABLE'::character varying, 'EXPIRED'::character varying, 'CONSUMED'::character varying, 'RESERVED'::character varying])::text[])))
);


--
-- Name: user_inventory_inventory_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.user_inventory ALTER COLUMN inventory_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_inventory_inventory_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_preferences; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_preferences (
    up_id bigint NOT NULL,
    context_json text,
    created_at timestamp(6) with time zone,
    expires_at timestamp(6) with time zone,
    is_active boolean,
    item_name character varying(255),
    occurrence_count integer,
    preference_type character varying(30) NOT NULL,
    preference_value text,
    priority integer,
    updated_at timestamp(6) with time zone,
    challenge_id bigint,
    food_id bigint,
    user_id bigint NOT NULL,
    CONSTRAINT user_preferences_preference_type_check CHECK (((preference_type)::text = ANY ((ARRAY['DISLIKED_FOOD'::character varying, 'LIKED_FOOD'::character varying, 'SKIPPED_EXERCISE'::character varying, 'FAVORITE_EXERCISE'::character varying, 'COOKING_EQUIPMENT'::character varying, 'DIETARY_RESTRICTION'::character varying, 'MEAL_PREP_TIME'::character varying, 'WORK_SCHEDULE'::character varying])::text[])))
);


--
-- Name: user_preferences_up_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.user_preferences ALTER COLUMN up_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_preferences_up_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_training; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_training (
    ut_id bigint NOT NULL,
    completed_days integer,
    completion_percentage double precision,
    current_day integer,
    end_date date,
    program_id character varying(20),
    start_date date,
    status character varying(20) DEFAULT 'active'::character varying,
    total_weeks integer,
    week_number integer,
    tp_id bigint NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: user_training_sessions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_training_sessions (
    id bigint NOT NULL,
    cardio text,
    cooldown text,
    created_at timestamp(6) with time zone,
    day_number integer NOT NULL,
    duration_minutes integer NOT NULL,
    estimated_calories_burned integer NOT NULL,
    muscle_groups_targeted text,
    notes text,
    is_rest_day boolean NOT NULL,
    session_type character varying(50) NOT NULL,
    training_plan_id bigint NOT NULL,
    updated_at timestamp(6) with time zone,
    user_id bigint NOT NULL,
    ut_id bigint NOT NULL,
    warmup text
);


--
-- Name: user_training_sessions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.user_training_sessions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_training_sessions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_training_ut_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.user_training ALTER COLUMN ut_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_training_ut_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    user_id bigint NOT NULL,
    created_at timestamp(6) with time zone,
    email character varying(255) NOT NULL,
    full_name character varying(255),
    last_login_at timestamp(6) with time zone,
    link_image character varying(500),
    password character varying(255) NOT NULL,
    points integer,
    is_active character varying(20),
    streak_count integer,
    updated_at timestamp(6) with time zone,
    username character varying(100) NOT NULL,
    role_id bigint
);


--
-- Name: users_user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN user_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ai_evaluation_logs ai_evaluation_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ai_evaluation_logs
    ADD CONSTRAINT ai_evaluation_logs_pkey PRIMARY KEY (ael_id);


--
-- Name: ai_model_events ai_model_events_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ai_model_events
    ADD CONSTRAINT ai_model_events_pkey PRIMARY KEY (event_id);


--
-- Name: body_metric_history body_metric_history_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.body_metric_history
    ADD CONSTRAINT body_metric_history_pkey PRIMARY KEY (bmh_id);


--
-- Name: budget_tracking budget_tracking_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.budget_tracking
    ADD CONSTRAINT budget_tracking_pkey PRIMARY KEY (bt_id);


--
-- Name: challenge_exercises challenge_exercises_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.challenge_exercises
    ADD CONSTRAINT challenge_exercises_pkey PRIMARY KEY (challenge_id, exercise_id);


--
-- Name: challenges challenges_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.challenges
    ADD CONSTRAINT challenges_pkey PRIMARY KEY (challenge_id);


--
-- Name: daily_nutrition_logs daily_nutrition_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.daily_nutrition_logs
    ADD CONSTRAINT daily_nutrition_logs_pkey PRIMARY KEY (dnl_id);


--
-- Name: daily_training_logs daily_training_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.daily_training_logs
    ADD CONSTRAINT daily_training_logs_pkey PRIMARY KEY (dtl_id);


--
-- Name: dish_ingredients dish_ingredients_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dish_ingredients
    ADD CONSTRAINT dish_ingredients_pkey PRIMARY KEY (dish_ingredient_id);


--
-- Name: dishes dishes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dishes
    ADD CONSTRAINT dishes_pkey PRIMARY KEY (dish_id);


--
-- Name: exercises exercises_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exercises
    ADD CONSTRAINT exercises_pkey PRIMARY KEY (exercise_id);


--
-- Name: foods foods_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.foods
    ADD CONSTRAINT foods_pkey PRIMARY KEY (food_id);


--
-- Name: goals goals_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.goals
    ADD CONSTRAINT goals_pkey PRIMARY KEY (goal_id);


--
-- Name: health_profile health_profile_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.health_profile
    ADD CONSTRAINT health_profile_pkey PRIMARY KEY (id);


--
-- Name: information_body_user information_body_user_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.information_body_user
    ADD CONSTRAINT information_body_user_pkey PRIMARY KEY (info_id);


--
-- Name: notifications notifications_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_pkey PRIMARY KEY (notification_id);


--
-- Name: personalized_meal_details personalized_meal_details_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.personalized_meal_details
    ADD CONSTRAINT personalized_meal_details_pkey PRIMARY KEY (pmd_id);


--
-- Name: personalized_meal_items personalized_meal_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.personalized_meal_items
    ADD CONSTRAINT personalized_meal_items_pkey PRIMARY KEY (pmi_id);


--
-- Name: personalized_nutrition_plans personalized_nutrition_plans_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.personalized_nutrition_plans
    ADD CONSTRAINT personalized_nutrition_plans_pkey PRIMARY KEY (pnp_id);


--
-- Name: personalized_plan_detail personalized_plan_detail_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.personalized_plan_detail
    ADD CONSTRAINT personalized_plan_detail_pkey PRIMARY KEY (ppd_id);


--
-- Name: plan_version_history plan_version_history_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plan_version_history
    ADD CONSTRAINT plan_version_history_pkey PRIMARY KEY (pvh_id);


--
-- Name: program_templates program_templates_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.program_templates
    ADD CONSTRAINT program_templates_pkey PRIMARY KEY (id);


--
-- Name: reports reports_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reports
    ADD CONSTRAINT reports_pkey PRIMARY KEY (report_id);


--
-- Name: reward_redemptions reward_redemptions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reward_redemptions
    ADD CONSTRAINT reward_redemptions_pkey PRIMARY KEY (rr_id);


--
-- Name: rewards rewards_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rewards
    ADD CONSTRAINT rewards_pkey PRIMARY KEY (reward_id);


--
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (role_id);


--
-- Name: training_plan_details training_plan_details_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.training_plan_details
    ADD CONSTRAINT training_plan_details_pkey PRIMARY KEY (tpd_id);


--
-- Name: training_plans training_plans_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.training_plans
    ADD CONSTRAINT training_plans_pkey PRIMARY KEY (tp_id);


--
-- Name: transactions transactions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT transactions_pkey PRIMARY KEY (tx_id);


--
-- Name: health_profile uk40afa6nkosuxjbbhd9xysqlb5; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.health_profile
    ADD CONSTRAINT uk40afa6nkosuxjbbhd9xysqlb5 UNIQUE (user_id);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: dish_ingredients uk_dish_food; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dish_ingredients
    ADD CONSTRAINT uk_dish_food UNIQUE (dish_id, food_id);


--
-- Name: user_training_sessions uk_user_training_sessions_ut_day; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_training_sessions
    ADD CONSTRAINT uk_user_training_sessions_ut_day UNIQUE (ut_id, day_number);


--
-- Name: users ukr43af9ap4edm43mmtq01oddj6; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username);


--
-- Name: user_body_profile user_body_profile_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_body_profile
    ADD CONSTRAINT user_body_profile_pkey PRIMARY KEY (id);


--
-- Name: user_challenges user_challenges_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_challenges
    ADD CONSTRAINT user_challenges_pkey PRIMARY KEY (uc_id);


--
-- Name: user_inventory user_inventory_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_inventory
    ADD CONSTRAINT user_inventory_pkey PRIMARY KEY (inventory_id);


--
-- Name: user_preferences user_preferences_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_preferences
    ADD CONSTRAINT user_preferences_pkey PRIMARY KEY (up_id);


--
-- Name: user_training user_training_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_training
    ADD CONSTRAINT user_training_pkey PRIMARY KEY (ut_id);


--
-- Name: user_training_sessions user_training_sessions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_training_sessions
    ADD CONSTRAINT user_training_sessions_pkey PRIMARY KEY (id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (user_id);


--
-- Name: idx_ael_challenge; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ael_challenge ON public.ai_evaluation_logs USING btree (challenge_id);


--
-- Name: idx_ael_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ael_status ON public.ai_evaluation_logs USING btree (status);


--
-- Name: idx_ael_user_challenge; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ael_user_challenge ON public.ai_evaluation_logs USING btree (user_challenge_id);


--
-- Name: idx_ael_user_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ael_user_created ON public.ai_evaluation_logs USING btree (user_id, created_at);


--
-- Name: idx_ame_uc_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ame_uc_created ON public.ai_model_events USING btree (uc_id, created_at);


--
-- Name: idx_ame_user_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ame_user_created ON public.ai_model_events USING btree (user_id, created_at);


--
-- Name: idx_bt_ai_compliance; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_bt_ai_compliance ON public.budget_tracking USING btree (ai_stayed_within_budget);


--
-- Name: idx_bt_user_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_bt_user_date ON public.budget_tracking USING btree (user_id, tracking_date);


--
-- Name: idx_bt_week; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_bt_week ON public.budget_tracking USING btree (user_id, week_start_date);


--
-- Name: idx_di_dish; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_di_dish ON public.dish_ingredients USING btree (dish_id);


--
-- Name: idx_di_food; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_di_food ON public.dish_ingredients USING btree (food_id);


--
-- Name: idx_dish_name; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_dish_name ON public.dishes USING btree (dish_name);


--
-- Name: idx_dish_role; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_dish_role ON public.dishes USING btree (dish_role);


--
-- Name: idx_dtl_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_dtl_status ON public.daily_training_logs USING btree (status);


--
-- Name: idx_dtl_user_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_dtl_user_date ON public.daily_training_logs USING btree (user_id, training_date);


--
-- Name: idx_dtl_user_plan; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_dtl_user_plan ON public.daily_training_logs USING btree (user_id, tp_id);


--
-- Name: idx_notif_type; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_notif_type ON public.notifications USING btree (type);


--
-- Name: idx_notif_user_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_notif_user_created ON public.notifications USING btree (user_id, created_at);


--
-- Name: idx_notif_user_read; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_notif_user_read ON public.notifications USING btree (user_id, is_read);


--
-- Name: idx_pmd_eaten; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_pmd_eaten ON public.personalized_meal_details USING btree (was_eaten);


--
-- Name: idx_pmd_meal_type; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_pmd_meal_type ON public.personalized_meal_details USING btree (meal_type);


--
-- Name: idx_pmd_plan_day; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_pmd_plan_day ON public.personalized_meal_details USING btree (pnp_id, day_number);


--
-- Name: idx_pmi_food; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_pmi_food ON public.personalized_meal_items USING btree (food_id);


--
-- Name: idx_pmi_pmd; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_pmi_pmd ON public.personalized_meal_items USING btree (pmd_id);


--
-- Name: idx_pnp_ai_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_pnp_ai_id ON public.personalized_nutrition_plans USING btree (ai_plan_id);


--
-- Name: idx_pnp_dates; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_pnp_dates ON public.personalized_nutrition_plans USING btree (start_date, end_date);


--
-- Name: idx_pnp_user_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_pnp_user_status ON public.personalized_nutrition_plans USING btree (user_id, status);


--
-- Name: idx_pvh_parent; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_pvh_parent ON public.plan_version_history USING btree (parent_version_id);


--
-- Name: idx_pvh_user_plan; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_pvh_user_plan ON public.plan_version_history USING btree (user_id, plan_type, plan_id);


--
-- Name: idx_pvh_version; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_pvh_version ON public.plan_version_history USING btree (version_number);


--
-- Name: idx_uc_challenge; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_uc_challenge ON public.user_challenges USING btree (challenge_id);


--
-- Name: idx_uc_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_uc_status ON public.user_challenges USING btree (status);


--
-- Name: idx_uc_user_submitted; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_uc_user_submitted ON public.user_challenges USING btree (user_id, submitted_at);


--
-- Name: idx_ui_expiry; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ui_expiry ON public.user_inventory USING btree (expiry_date);


--
-- Name: idx_ui_food; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ui_food ON public.user_inventory USING btree (food_id);


--
-- Name: idx_ui_user_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ui_user_status ON public.user_inventory USING btree (user_id, status);


--
-- Name: idx_up_item; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_up_item ON public.user_preferences USING btree (item_name);


--
-- Name: idx_up_user_type; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_up_user_type ON public.user_preferences USING btree (user_id, preference_type);


--
-- Name: budget_tracking fk1b3rtfiij5flsl9geah919mt7; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.budget_tracking
    ADD CONSTRAINT fk1b3rtfiij5flsl9geah919mt7 FOREIGN KEY (pnp_id) REFERENCES public.personalized_nutrition_plans(pnp_id);


--
-- Name: reward_redemptions fk1fl7vw3n1k600ewfdmcaoau12; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reward_redemptions
    ADD CONSTRAINT fk1fl7vw3n1k600ewfdmcaoau12 FOREIGN KEY (reward_id) REFERENCES public.rewards(reward_id);


--
-- Name: reports fk2o32rer9hfweeylg7x8ut8rj2; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reports
    ADD CONSTRAINT fk2o32rer9hfweeylg7x8ut8rj2 FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: user_training fk37jltyeavop89ac5x8x0lnh2c; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_training
    ADD CONSTRAINT fk37jltyeavop89ac5x8x0lnh2c FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: budget_tracking fk3rjb31bsojw9cctetjw9rdimd; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.budget_tracking
    ADD CONSTRAINT fk3rjb31bsojw9cctetjw9rdimd FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: user_body_profile fk4pqpljkq4jduo4p3v6gjucn3y; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_body_profile
    ADD CONSTRAINT fk4pqpljkq4jduo4p3v6gjucn3y FOREIGN KEY (goal_id) REFERENCES public.goals(goal_id);


--
-- Name: user_inventory fk57dx75taqcx8qkfu13bc2vrxu; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_inventory
    ADD CONSTRAINT fk57dx75taqcx8qkfu13bc2vrxu FOREIGN KEY (food_id) REFERENCES public.foods(food_id);


--
-- Name: daily_nutrition_logs fk5rpt7n1kekob8fdp3mkg3l648; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.daily_nutrition_logs
    ADD CONSTRAINT fk5rpt7n1kekob8fdp3mkg3l648 FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: information_body_user fk60ivl87vlu9lxpb1gkn18ecgr; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.information_body_user
    ADD CONSTRAINT fk60ivl87vlu9lxpb1gkn18ecgr FOREIGN KEY (goal_id) REFERENCES public.goals(goal_id);


--
-- Name: personalized_plan_detail fk6keu71piglgwensgld7jrsum3; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.personalized_plan_detail
    ADD CONSTRAINT fk6keu71piglgwensgld7jrsum3 FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: reward_redemptions fk7mlsj71t0guywfoblp1o3q56a; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reward_redemptions
    ADD CONSTRAINT fk7mlsj71t0guywfoblp1o3q56a FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: ai_evaluation_logs fk87jj51hw7a4hk6nf62c7ee7u1; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ai_evaluation_logs
    ADD CONSTRAINT fk87jj51hw7a4hk6nf62c7ee7u1 FOREIGN KEY (user_challenge_id) REFERENCES public.user_challenges(uc_id);


--
-- Name: ai_model_events fk8o0i3ocmfhxgi63qq2nmla5uw; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ai_model_events
    ADD CONSTRAINT fk8o0i3ocmfhxgi63qq2nmla5uw FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: notifications fk9y21adhxn0ayjhfocscqox7bh; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT fk9y21adhxn0ayjhfocscqox7bh FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: training_plan_details fka4jc9gy4rsj60fdjbhrr8tic1; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.training_plan_details
    ADD CONSTRAINT fka4jc9gy4rsj60fdjbhrr8tic1 FOREIGN KEY (exercise_id) REFERENCES public.exercises(exercise_id);


--
-- Name: ai_evaluation_logs fkaecu0s4wgwq205sif0pei7wky; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ai_evaluation_logs
    ADD CONSTRAINT fkaecu0s4wgwq205sif0pei7wky FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: personalized_meal_details fkb4wr8gjhsgh1warykf0cuwfws; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.personalized_meal_details
    ADD CONSTRAINT fkb4wr8gjhsgh1warykf0cuwfws FOREIGN KEY (pnp_id) REFERENCES public.personalized_nutrition_plans(pnp_id);


--
-- Name: dish_ingredients fkbhivhxrdibnjx2unpalmvc0e8; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dish_ingredients
    ADD CONSTRAINT fkbhivhxrdibnjx2unpalmvc0e8 FOREIGN KEY (dish_id) REFERENCES public.dishes(dish_id);


--
-- Name: user_body_profile fkbt5so7i1dtrxhqlydfaa52wai; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_body_profile
    ADD CONSTRAINT fkbt5so7i1dtrxhqlydfaa52wai FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: daily_training_logs fkbvjnkj4w4vkmv81y9uj8sgyda; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.daily_training_logs
    ADD CONSTRAINT fkbvjnkj4w4vkmv81y9uj8sgyda FOREIGN KEY (exercise_id) REFERENCES public.exercises(exercise_id);


--
-- Name: user_challenges fkcdjf32e49p3wb497fpxklkon; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_challenges
    ADD CONSTRAINT fkcdjf32e49p3wb497fpxklkon FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: user_inventory fkdl20oug3qb2wki6g9824mbb9h; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_inventory
    ADD CONSTRAINT fkdl20oug3qb2wki6g9824mbb9h FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: training_plans fkdnw6dnv0e8lxgbk95n67hw8m4; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.training_plans
    ADD CONSTRAINT fkdnw6dnv0e8lxgbk95n67hw8m4 FOREIGN KEY (goal_id) REFERENCES public.goals(goal_id);


--
-- Name: ai_model_events fkem4707qe2e81tq21ply1ct7pk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ai_model_events
    ADD CONSTRAINT fkem4707qe2e81tq21ply1ct7pk FOREIGN KEY (uc_id) REFERENCES public.user_challenges(uc_id);


--
-- Name: user_preferences fkepakpib0qnm82vmaiismkqf88; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_preferences
    ADD CONSTRAINT fkepakpib0qnm82vmaiismkqf88 FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: food_allergens fkeu9uxuaat96p1xfwo0bb74c7g; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.food_allergens
    ADD CONSTRAINT fkeu9uxuaat96p1xfwo0bb74c7g FOREIGN KEY (food_id) REFERENCES public.foods(food_id);


--
-- Name: personalized_meal_details fkf3vv5k5hhjd490d4li2t12p2r; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.personalized_meal_details
    ADD CONSTRAINT fkf3vv5k5hhjd490d4li2t12p2r FOREIGN KEY (dish_id) REFERENCES public.dishes(dish_id);


--
-- Name: daily_training_logs fkf6luah9rm5o1w8s39olcovu0g; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.daily_training_logs
    ADD CONSTRAINT fkf6luah9rm5o1w8s39olcovu0g FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: dish_ingredients fkgpumyrwxqx12ti5npbs3sn33i; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dish_ingredients
    ADD CONSTRAINT fkgpumyrwxqx12ti5npbs3sn33i FOREIGN KEY (food_id) REFERENCES public.foods(food_id);


--
-- Name: reports fkh54goasq9qmd9a5ql63cr4l89; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reports
    ADD CONSTRAINT fkh54goasq9qmd9a5ql63cr4l89 FOREIGN KEY (ai_evaluation_log_id) REFERENCES public.ai_evaluation_logs(ael_id);


--
-- Name: plan_version_history fkhqlynx28x9d1mkymg37iwnhei; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plan_version_history
    ADD CONSTRAINT fkhqlynx28x9d1mkymg37iwnhei FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: challenges fkhucyjkb2r5eu6kk0dybmdit2o; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.challenges
    ADD CONSTRAINT fkhucyjkb2r5eu6kk0dybmdit2o FOREIGN KEY (goal_id) REFERENCES public.goals(goal_id);


--
-- Name: user_preferences fkhxcmdtmrolj0cma9xsgb462kk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_preferences
    ADD CONSTRAINT fkhxcmdtmrolj0cma9xsgb462kk FOREIGN KEY (food_id) REFERENCES public.foods(food_id);


--
-- Name: training_plan_details fkhyuowgrccyfxs32j617xvnp6i; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.training_plan_details
    ADD CONSTRAINT fkhyuowgrccyfxs32j617xvnp6i FOREIGN KEY (tp_id) REFERENCES public.training_plans(tp_id);


--
-- Name: health_profile fki5cnr23siyeibdnnk66t1cqmq; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.health_profile
    ADD CONSTRAINT fki5cnr23siyeibdnnk66t1cqmq FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: challenge_exercises fkjebtnkj0ncd7kp3durdgkxh8t; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.challenge_exercises
    ADD CONSTRAINT fkjebtnkj0ncd7kp3durdgkxh8t FOREIGN KEY (challenge_id) REFERENCES public.challenges(challenge_id);


--
-- Name: exercises fkjsflh963ev9nnttfqf2xannt9; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exercises
    ADD CONSTRAINT fkjsflh963ev9nnttfqf2xannt9 FOREIGN KEY (regression_exercise_id) REFERENCES public.exercises(exercise_id);


--
-- Name: personalized_meal_items fklh5r0idyqod1ghmtwfxw968un; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.personalized_meal_items
    ADD CONSTRAINT fklh5r0idyqod1ghmtwfxw968un FOREIGN KEY (food_id) REFERENCES public.foods(food_id);


--
-- Name: body_metric_history fkm8jbsw1x39ow6aibpnlfp7mbx; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.body_metric_history
    ADD CONSTRAINT fkm8jbsw1x39ow6aibpnlfp7mbx FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: personalized_plan_detail fkmkroxw97fui7q1dk7qif70gyy; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.personalized_plan_detail
    ADD CONSTRAINT fkmkroxw97fui7q1dk7qif70gyy FOREIGN KEY (exercise_id) REFERENCES public.exercises(exercise_id);


--
-- Name: exercises fkmuedcf4visofxw7qrmpqy8iov; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exercises
    ADD CONSTRAINT fkmuedcf4visofxw7qrmpqy8iov FOREIGN KEY (progression_exercise_id) REFERENCES public.exercises(exercise_id);


--
-- Name: information_body_user fknr0q8xkv1pfw2xwixtj6ylrjn; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.information_body_user
    ADD CONSTRAINT fknr0q8xkv1pfw2xwixtj6ylrjn FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: reports fkntrfx4mhbc370jj5hlxgj8t7; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reports
    ADD CONSTRAINT fkntrfx4mhbc370jj5hlxgj8t7 FOREIGN KEY (challenge_id) REFERENCES public.challenges(challenge_id);


--
-- Name: reports fkom6ouaxsqiyvh58f06xig3ut3; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reports
    ADD CONSTRAINT fkom6ouaxsqiyvh58f06xig3ut3 FOREIGN KEY (assigned_to_user_id) REFERENCES public.users(user_id);


--
-- Name: plan_version_history fkonbnkk51nai69ovch6vrqojo; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plan_version_history
    ADD CONSTRAINT fkonbnkk51nai69ovch6vrqojo FOREIGN KEY (parent_version_id) REFERENCES public.plan_version_history(pvh_id);


--
-- Name: challenge_exercises fkooyfk6b9q0ugd9c3qytbs3rho; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.challenge_exercises
    ADD CONSTRAINT fkooyfk6b9q0ugd9c3qytbs3rho FOREIGN KEY (exercise_id) REFERENCES public.exercises(exercise_id);


--
-- Name: users fkp56c1712k691lhsyewcssf40f; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fkp56c1712k691lhsyewcssf40f FOREIGN KEY (role_id) REFERENCES public.roles(role_id);


--
-- Name: user_training fkp7t88mvr487apvy8bmmo8kckb; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_training
    ADD CONSTRAINT fkp7t88mvr487apvy8bmmo8kckb FOREIGN KEY (tp_id) REFERENCES public.training_plans(tp_id);


--
-- Name: reports fkpggbe8lxgwufx95m3cuyxly8t; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reports
    ADD CONSTRAINT fkpggbe8lxgwufx95m3cuyxly8t FOREIGN KEY (user_challenge_id) REFERENCES public.user_challenges(uc_id);


--
-- Name: ai_model_events fkpi91f3n61f670mjddg4d403ed; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ai_model_events
    ADD CONSTRAINT fkpi91f3n61f670mjddg4d403ed FOREIGN KEY (exercise_id) REFERENCES public.exercises(exercise_id);


--
-- Name: transactions fkqwv7rmvc8va8rep7piikrojds; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT fkqwv7rmvc8va8rep7piikrojds FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: ai_evaluation_logs fkr6w9gmjbq9b1s6drvn367uvco; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ai_evaluation_logs
    ADD CONSTRAINT fkr6w9gmjbq9b1s6drvn367uvco FOREIGN KEY (challenge_id) REFERENCES public.challenges(challenge_id);


--
-- Name: user_preferences fkrupr24jls8wuyqvew7seerhn2; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_preferences
    ADD CONSTRAINT fkrupr24jls8wuyqvew7seerhn2 FOREIGN KEY (challenge_id) REFERENCES public.challenges(challenge_id);


--
-- Name: personalized_meal_items fks8bdiadkdvsi2wgwt6b96g9b6; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.personalized_meal_items
    ADD CONSTRAINT fks8bdiadkdvsi2wgwt6b96g9b6 FOREIGN KEY (dish_id) REFERENCES public.dishes(dish_id);


--
-- Name: daily_training_logs fkt6t3ma63369s6w3vjjg4wtnif; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.daily_training_logs
    ADD CONSTRAINT fkt6t3ma63369s6w3vjjg4wtnif FOREIGN KEY (tp_id) REFERENCES public.training_plans(tp_id);


--
-- Name: user_challenges fktaajflq2v15ya0kct9woncmft; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_challenges
    ADD CONSTRAINT fktaajflq2v15ya0kct9woncmft FOREIGN KEY (challenge_id) REFERENCES public.challenges(challenge_id);


--
-- Name: ai_model_events fkte4r93gxqm1e4fv92lnne12c3; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ai_model_events
    ADD CONSTRAINT fkte4r93gxqm1e4fv92lnne12c3 FOREIGN KEY (challenge_id) REFERENCES public.challenges(challenge_id);


--
-- Name: personalized_nutrition_plans fktijfvmffv80ru2k036gjdtkbs; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.personalized_nutrition_plans
    ADD CONSTRAINT fktijfvmffv80ru2k036gjdtkbs FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: personalized_meal_items fktna6ekn7i1a8ya32jq4rukswo; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.personalized_meal_items
    ADD CONSTRAINT fktna6ekn7i1a8ya32jq4rukswo FOREIGN KEY (pmd_id) REFERENCES public.personalized_meal_details(pmd_id);


--
-- PostgreSQL database dump complete
--


