 -- V11: Exercise Seed Expansion — 28 → 60 exercises
-- Ensures 4 weeks of non-repeating sessions across Push/Pull/Legs/Core/Cardio/Mobility
-- All exercises are bodyweight or use minimal equipment (bodyweight, band, dumbbell)

INSERT INTO exercises (
    exercise_name, description, difficulty_level, exercise_type, movement_pattern,
    primary_muscle, secondary_muscles, required_equipment,
    spinal_loading, knee_dominant, shoulder_overhead, high_impact, wrist_loading,
    default_sets, default_reps, default_rest_seconds,
    met_value, force_type, exercise_category,
    rpe_min, rpe_max, tempo,
    suitable_for_senior, suitable_for_overweight, is_bilateral,
    status
) VALUES

-- ─── PUSH (6 exercises) ───────────────────────────────────────────────────
('Decline Push Up',
 'Push up with feet elevated on a surface, targeting upper chest and front deltoids.',
 'MEDIUM', 'STRENGTH', 'PUSH',
 'Upper Chest', 'Front Deltoid,Triceps', 'BODYWEIGHT',
 FALSE, FALSE, FALSE, FALSE, TRUE,
 3, 10, 60, 6.5, 'PUSH', 'COMPOUND',
 6, 8, '3-0-1', FALSE, FALSE, TRUE, 'ACTIVE'),

('Pike Push Up',
 'Push up in an inverted V position, primarily targeting shoulders.',
 'MEDIUM', 'STRENGTH', 'PUSH',
 'Deltoid', 'Triceps,Upper Back', 'BODYWEIGHT',
 FALSE, FALSE, TRUE, FALSE, TRUE,
 3, 10, 60, 5.5, 'PUSH', 'COMPOUND',
 5, 7, '3-0-1', FALSE, FALSE, TRUE, 'ACTIVE'),

('Dip',
 'Parallel bar or bench dip targeting triceps and lower chest.',
 'MEDIUM', 'STRENGTH', 'PUSH',
 'Triceps', 'Lower Chest,Deltoid', 'BODYWEIGHT',
 FALSE, FALSE, FALSE, FALSE, TRUE,
 3, 10, 75, 6.0, 'PUSH', 'COMPOUND',
 6, 8, '3-0-1', FALSE, FALSE, TRUE, 'ACTIVE'),

('Shoulder Tap',
 'Plank position: alternate tapping each shoulder, challenges core stability and push endurance.',
 'MEDIUM', 'STRENGTH', 'PUSH',
 'Deltoid', 'Core,Chest,Triceps', 'BODYWEIGHT',
 FALSE, FALSE, FALSE, FALSE, TRUE,
 3, 12, 45, 4.5, 'PUSH', 'COMPOUND',
 4, 6, '1-1-1', TRUE, TRUE, FALSE, 'ACTIVE'),

('Wide Push Up',
 'Push up with hands wider than shoulder-width, emphasizing outer chest.',
 'EASY', 'STRENGTH', 'PUSH',
 'Chest', 'Triceps,Front Deltoid', 'BODYWEIGHT',
 FALSE, FALSE, FALSE, FALSE, TRUE,
 3, 12, 60, 5.5, 'PUSH', 'COMPOUND',
 4, 6, '3-0-1', TRUE, TRUE, TRUE, 'ACTIVE'),

('Overhead Press (Bodyweight)',
 'Standing overhead press motion using resistance band or improvised weight.',
 'MEDIUM', 'STRENGTH', 'PUSH',
 'Deltoid', 'Triceps,Upper Trapezius', 'BAND',
 FALSE, FALSE, TRUE, FALSE, FALSE,
 3, 12, 60, 4.0, 'PUSH', 'COMPOUND',
 5, 7, '3-0-1', FALSE, TRUE, TRUE, 'ACTIVE'),

-- ─── PULL (6 exercises) ───────────────────────────────────────────────────
('Inverted Row',
 'Lie under a bar or table, pull chest up to it. Great pull up regression.',
 'EASY', 'STRENGTH', 'PULL',
 'Upper Back', 'Biceps,Rear Deltoid', 'BODYWEIGHT',
 FALSE, FALSE, FALSE, FALSE, FALSE,
 3, 10, 60, 5.0, 'PULL', 'COMPOUND',
 4, 6, '3-1-1', TRUE, TRUE, TRUE, 'ACTIVE'),

('Band Pull Apart',
 'Hold a resistance band at chest height and pull it apart, targeting rear deltoids.',
 'EASY', 'STRENGTH', 'PULL',
 'Rear Deltoid', 'Rhomboid,Trapezius', 'BAND',
 FALSE, FALSE, FALSE, FALSE, FALSE,
 3, 15, 45, 3.0, 'PULL', 'ISOLATION',
 3, 5, '2-1-2', TRUE, TRUE, TRUE, 'ACTIVE'),

('Face Pull (Band)',
 'Pull band toward face with elbows high, targeting rear deltoids and external rotators.',
 'EASY', 'STRENGTH', 'PULL',
 'Rear Deltoid', 'Rotator Cuff,Rhomboid', 'BAND',
 FALSE, FALSE, FALSE, FALSE, FALSE,
 3, 15, 45, 3.5, 'PULL', 'ISOLATION',
 3, 5, '2-1-2', TRUE, TRUE, TRUE, 'ACTIVE'),

('Superman',
 'Lie prone, lift arms and legs simultaneously. Targets erector spinae and glutes.',
 'EASY', 'STRENGTH', 'PULL',
 'Erector Spinae', 'Glutes,Rear Deltoid', 'BODYWEIGHT',
 FALSE, FALSE, FALSE, FALSE, FALSE,
 3, 12, 45, 3.0, 'PULL', 'ISOLATION',
 3, 5, '1-2-1', TRUE, TRUE, TRUE, 'ACTIVE'),

('Resistance Band Row',
 'Seated or standing row with resistance band, simulating cable row.',
 'EASY', 'STRENGTH', 'PULL',
 'Latissimus Dorsi', 'Biceps,Rhomboid', 'BAND',
 FALSE, FALSE, FALSE, FALSE, FALSE,
 3, 12, 60, 4.5, 'PULL', 'COMPOUND',
 4, 6, '3-1-1', TRUE, TRUE, TRUE, 'ACTIVE'),

('Chin Up',
 'Pull up with supinated (underhand) grip, more bicep engagement than pull up.',
 'HARD', 'STRENGTH', 'PULL',
 'Biceps', 'Latissimus Dorsi,Rear Deltoid', 'BODYWEIGHT',
 FALSE, FALSE, FALSE, FALSE, FALSE,
 3, 8, 90, 8.0, 'PULL', 'COMPOUND',
 7, 9, '3-0-1', FALSE, FALSE, TRUE, 'ACTIVE'),

-- ─── LEGS (8 exercises) ───────────────────────────────────────────────────
('Sumo Squat',
 'Wide stance squat targeting inner thighs and glutes more than standard squat.',
 'EASY', 'STRENGTH', 'LEGS',
 'Glutes', 'Inner Thigh,Quadriceps', 'BODYWEIGHT',
 FALSE, TRUE, FALSE, FALSE, FALSE,
 3, 12, 60, 5.0, 'LEGS', 'COMPOUND',
 4, 6, '3-1-1', TRUE, TRUE, TRUE, 'ACTIVE'),

('Lateral Lunge',
 'Step to the side and lower into a lunge, targeting inner thighs and glutes.',
 'MEDIUM', 'STRENGTH', 'LEGS',
 'Inner Thigh', 'Glutes,Quadriceps', 'BODYWEIGHT',
 FALSE, TRUE, FALSE, FALSE, FALSE,
 3, 10, 60, 5.0, 'LEGS', 'COMPOUND',
 5, 7, '3-0-1', TRUE, FALSE, FALSE, 'ACTIVE'),

('Wall Sit',
 'Isometric hold in seated position against a wall. Great for senior-friendly leg training.',
 'EASY', 'STRENGTH', 'LEGS',
 'Quadriceps', 'Glutes,Hamstrings', 'BODYWEIGHT',
 FALSE, TRUE, FALSE, FALSE, FALSE,
 3, 30, 60, 3.5, 'LEGS', 'ISOLATION',
 4, 6, '0-0-0', TRUE, TRUE, TRUE, 'ACTIVE'),

('Calf Raise',
 'Rise on toes, targeting gastrocnemius and soleus. Can be done single-leg.',
 'EASY', 'STRENGTH', 'LEGS',
 'Calves', 'Soleus', 'BODYWEIGHT',
 FALSE, FALSE, FALSE, FALSE, FALSE,
 3, 20, 45, 3.0, 'LEGS', 'ISOLATION',
 3, 5, '2-1-2', TRUE, TRUE, TRUE, 'ACTIVE'),

('Step Up',
 'Step onto a bench or stair, single-leg movement targeting quads and glutes.',
 'MEDIUM', 'STRENGTH', 'LEGS',
 'Quadriceps', 'Glutes,Hamstrings', 'BODYWEIGHT',
 FALSE, TRUE, FALSE, FALSE, FALSE,
 3, 10, 60, 5.0, 'LEGS', 'COMPOUND',
 5, 7, '2-0-1', TRUE, FALSE, FALSE, 'ACTIVE'),

('Bulgarian Split Squat',
 'Rear foot elevated split squat. Single-leg compound targeting quads and glutes.',
 'HARD', 'STRENGTH', 'LEGS',
 'Quadriceps', 'Glutes,Hamstrings', 'BODYWEIGHT',
 FALSE, TRUE, FALSE, FALSE, FALSE,
 3, 8, 75, 6.0, 'LEGS', 'COMPOUND',
 7, 9, '3-1-1', FALSE, FALSE, FALSE, 'ACTIVE'),

('Reverse Lunge',
 'Step backward into a lunge position, less knee stress than forward lunge.',
 'EASY', 'STRENGTH', 'LEGS',
 'Glutes', 'Quadriceps,Hamstrings', 'BODYWEIGHT',
 FALSE, TRUE, FALSE, FALSE, FALSE,
 3, 10, 60, 5.0, 'LEGS', 'COMPOUND',
 4, 6, '3-0-1', TRUE, TRUE, FALSE, 'ACTIVE'),

('Single Leg Deadlift',
 'Balance on one leg, hinge forward with weights or bodyweight. Targets hamstrings and glutes.',
 'MEDIUM', 'STRENGTH', 'LEGS',
 'Hamstrings', 'Glutes,Erector Spinae', 'BODYWEIGHT',
 TRUE, FALSE, FALSE, FALSE, FALSE,
 3, 8, 75, 5.5, 'LEGS', 'COMPOUND',
 6, 8, '3-1-1', FALSE, FALSE, FALSE, 'ACTIVE'),

-- ─── CORE (7 exercises) ───────────────────────────────────────────────────
('Dead Bug',
 'Lie on back, extend opposite arm and leg while keeping lower back flat. Safe spinal stability.',
 'EASY', 'STRENGTH', 'CORE',
 'Transverse Abdominis', 'Hip Flexors,Erector Spinae', 'BODYWEIGHT',
 FALSE, FALSE, FALSE, FALSE, FALSE,
 3, 10, 45, 3.0, 'CORE', 'ISOLATION',
 3, 5, '3-0-1', TRUE, TRUE, FALSE, 'ACTIVE'),

('Bird Dog',
 'On hands and knees, extend opposite arm and leg. Great for lumbar stability.',
 'EASY', 'STRENGTH', 'CORE',
 'Erector Spinae', 'Glutes,Core', 'BODYWEIGHT',
 FALSE, FALSE, FALSE, FALSE, FALSE,
 3, 10, 45, 3.0, 'CORE', 'ISOLATION',
 3, 5, '2-1-1', TRUE, TRUE, FALSE, 'ACTIVE'),

('Russian Twist',
 'Seated rotation, targeting obliques. Use bodyweight or hold a weight.',
 'MEDIUM', 'STRENGTH', 'CORE',
 'Obliques', 'Rectus Abdominis', 'BODYWEIGHT',
 FALSE, FALSE, FALSE, FALSE, FALSE,
 3, 20, 45, 3.5, 'CORE', 'ISOLATION',
 4, 6, '1-0-1', FALSE, TRUE, TRUE, 'ACTIVE'),

('Hollow Hold',
 'Lie on back, raise arms and legs slightly, hold position. Advanced core stability.',
 'HARD', 'STRENGTH', 'CORE',
 'Rectus Abdominis', 'Hip Flexors,Obliques', 'BODYWEIGHT',
 FALSE, FALSE, FALSE, FALSE, FALSE,
 3, 20, 60, 3.5, 'CORE', 'ISOLATION',
 6, 8, '0-0-0', FALSE, FALSE, TRUE, 'ACTIVE'),

('Leg Raise',
 'Lie on back and raise straight legs to 90 degrees. Lower without touching floor.',
 'MEDIUM', 'STRENGTH', 'CORE',
 'Hip Flexors', 'Rectus Abdominis', 'BODYWEIGHT',
 FALSE, FALSE, FALSE, FALSE, FALSE,
 3, 12, 60, 3.5, 'CORE', 'ISOLATION',
 5, 7, '3-1-1', FALSE, FALSE, TRUE, 'ACTIVE'),

('Bicycle Crunch',
 'Alternate elbow to opposite knee in cycling motion, targeting obliques.',
 'MEDIUM', 'STRENGTH', 'CORE',
 'Obliques', 'Rectus Abdominis,Hip Flexors', 'BODYWEIGHT',
 FALSE, FALSE, FALSE, FALSE, FALSE,
 3, 20, 45, 3.5, 'CORE', 'ISOLATION',
 4, 6, '1-0-1', TRUE, TRUE, TRUE, 'ACTIVE'),

('Side Plank',
 'Lateral plank position, targeting obliques and hip abductors.',
 'MEDIUM', 'STRENGTH', 'CORE',
 'Obliques', 'Hip Abductors,Shoulders', 'BODYWEIGHT',
 FALSE, FALSE, FALSE, FALSE, TRUE,
 3, 30, 60, 3.0, 'CORE', 'ISOLATION',
 4, 6, '0-0-0', TRUE, TRUE, FALSE, 'ACTIVE'),

-- ─── CARDIO (5 exercises) ─────────────────────────────────────────────────
('High Knees',
 'Run in place with knees driving up to waist height. Elevates heart rate quickly.',
 'MEDIUM', 'CARDIO', 'CARDIO',
 'Hip Flexors', 'Quadriceps,Calves,Core', 'BODYWEIGHT',
 FALSE, FALSE, FALSE, TRUE, FALSE,
 3, 30, 30, 8.0, 'CARDIO', 'COMPOUND',
 6, 8, '1-0-1', FALSE, FALSE, FALSE, 'ACTIVE'),

('Jump Squat',
 'Squat down then explode upward. High power output and calorie burn.',
 'HARD', 'CARDIO', 'LEGS',
 'Quadriceps', 'Glutes,Calves', 'BODYWEIGHT',
 FALSE, TRUE, FALSE, TRUE, FALSE,
 3, 10, 60, 9.0, 'LEGS', 'COMPOUND',
 7, 9, '1-0-X', FALSE, FALSE, TRUE, 'ACTIVE'),

('Skater Jump',
 'Lateral explosive jump from foot to foot, mimicking ice skating.',
 'MEDIUM', 'CARDIO', 'CARDIO',
 'Glutes', 'Quadriceps,Calves', 'BODYWEIGHT',
 FALSE, TRUE, FALSE, TRUE, FALSE,
 3, 20, 45, 8.0, 'CARDIO', 'COMPOUND',
 6, 8, '1-0-X', FALSE, FALSE, FALSE, 'ACTIVE'),

('Speed Squat',
 'Fast bodyweight squats focusing on speed, not depth. Cardio + leg endurance.',
 'MEDIUM', 'CARDIO', 'LEGS',
 'Quadriceps', 'Glutes,Calves', 'BODYWEIGHT',
 FALSE, TRUE, FALSE, TRUE, FALSE,
 3, 20, 30, 7.5, 'LEGS', 'COMPOUND',
 6, 8, '1-0-1', FALSE, FALSE, TRUE, 'ACTIVE'),

('Shadow Boxing',
 'Punch combinations in the air. Cardio + shoulder endurance + coordination.',
 'EASY', 'CARDIO', 'CARDIO',
 'Deltoid', 'Core,Calves,Triceps', 'BODYWEIGHT',
 FALSE, FALSE, FALSE, FALSE, FALSE,
 3, 60, 30, 7.0, 'CARDIO', 'COMPOUND',
 5, 7, '1-0-1', TRUE, TRUE, TRUE, 'ACTIVE'),

-- ─── MOBILITY (5 exercises) ───────────────────────────────────────────────
('Hip 90/90 Stretch',
 'Sit with both knees at 90 degrees, rotate between internal and external hip rotation.',
 'EASY', 'MOBILITY', 'MOBILITY',
 'Hip Rotators', 'Glutes,Hip Flexors', 'BODYWEIGHT',
 FALSE, FALSE, FALSE, FALSE, FALSE,
 2, 10, 30, 2.0, 'MOBILITY', 'MOBILITY',
 2, 4, '0-5-0', TRUE, TRUE, FALSE, 'ACTIVE'),

('Ankle Circle',
 'Rotate ankle in full circles, improving dorsiflexion and injury prevention.',
 'EASY', 'MOBILITY', 'MOBILITY',
 'Ankle', 'Calves,Peroneal', 'BODYWEIGHT',
 FALSE, FALSE, FALSE, FALSE, FALSE,
 2, 20, 30, 1.5, 'MOBILITY', 'MOBILITY',
 1, 2, '0-0-0', TRUE, TRUE, FALSE, 'ACTIVE'),

('Thoracic Rotation',
 'Seated or kneeling rotation of upper spine, improving T-spine mobility.',
 'EASY', 'MOBILITY', 'MOBILITY',
 'Thoracic Spine', 'Obliques,Rhomboid', 'BODYWEIGHT',
 FALSE, FALSE, FALSE, FALSE, FALSE,
 2, 10, 30, 2.0, 'MOBILITY', 'MOBILITY',
 2, 3, '1-2-1', TRUE, TRUE, FALSE, 'ACTIVE'),

('Cat-Cow',
 'Alternating spinal flexion and extension on all-fours. Classic mobility warm-up.',
 'EASY', 'MOBILITY', 'MOBILITY',
 'Spine', 'Core,Hip Flexors', 'BODYWEIGHT',
 FALSE, FALSE, FALSE, FALSE, FALSE,
 2, 10, 30, 2.0, 'MOBILITY', 'MOBILITY',
 1, 3, '1-1-1', TRUE, TRUE, TRUE, 'ACTIVE'),

('World''s Greatest Stretch',
 'Lunge forward, rotate and reach up — targets hip flexors, thoracic spine, hamstrings.',
 'MEDIUM', 'MOBILITY', 'MOBILITY',
 'Hip Flexors', 'Thoracic Spine,Hamstrings', 'BODYWEIGHT',
 FALSE, TRUE, FALSE, FALSE, FALSE,
 2, 5, 30, 2.5, 'MOBILITY', 'MOBILITY',
 3, 5, '1-3-1', TRUE, FALSE, FALSE, 'ACTIVE')

ON CONFLICT DO NOTHING;
